almost done with adding combatants
modal appears and all data is passed to the combatant controller create.
issue is arising in the combatant model increment_name.
line 17 throws NoMethodError (undefined method `[]' for nil:NilClass):.
i'll need to do more analysis, however i have to sign off for the remainder of the day.